/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 9
#define LARGE_STATE_COUNT 8
#define SYMBOL_COUNT 22
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 2
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_comment = 1,
  sym_newline = 2,
  sym_tape_name = 3,
  anon_sym_LPARENstraight_RPAREN = 4,
  anon_sym_LPARENlooped_RPAREN = 5,
  sym_fixed_point = 6,
  sym_memory_order = 7,
  sym_op_noop = 8,
  sym_op_finish = 9,
  sym_op_signal = 10,
  sym_op_sign_test = 11,
  sym_op_transfer = 12,
  sym_op_search = 13,
  sym_op_layout = 14,
  sym_op_shift = 15,
  sym_arithmetic_order = 16,
  sym_source_file = 17,
  sym_tape_header = 18,
  sym_tape_mode = 19,
  sym_control_order = 20,
  aux_sym_source_file_repeat1 = 21,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [sym_newline] = "newline",
  [sym_tape_name] = "tape_name",
  [anon_sym_LPARENstraight_RPAREN] = "(straight)",
  [anon_sym_LPARENlooped_RPAREN] = "(looped)",
  [sym_fixed_point] = "fixed_point",
  [sym_memory_order] = "memory_order",
  [sym_op_noop] = "op_noop",
  [sym_op_finish] = "op_finish",
  [sym_op_signal] = "op_signal",
  [sym_op_sign_test] = "op_sign_test",
  [sym_op_transfer] = "op_transfer",
  [sym_op_search] = "op_search",
  [sym_op_layout] = "op_layout",
  [sym_op_shift] = "op_shift",
  [sym_arithmetic_order] = "arithmetic_order",
  [sym_source_file] = "source_file",
  [sym_tape_header] = "tape_header",
  [sym_tape_mode] = "tape_mode",
  [sym_control_order] = "control_order",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [sym_newline] = sym_newline,
  [sym_tape_name] = sym_tape_name,
  [anon_sym_LPARENstraight_RPAREN] = anon_sym_LPARENstraight_RPAREN,
  [anon_sym_LPARENlooped_RPAREN] = anon_sym_LPARENlooped_RPAREN,
  [sym_fixed_point] = sym_fixed_point,
  [sym_memory_order] = sym_memory_order,
  [sym_op_noop] = sym_op_noop,
  [sym_op_finish] = sym_op_finish,
  [sym_op_signal] = sym_op_signal,
  [sym_op_sign_test] = sym_op_sign_test,
  [sym_op_transfer] = sym_op_transfer,
  [sym_op_search] = sym_op_search,
  [sym_op_layout] = sym_op_layout,
  [sym_op_shift] = sym_op_shift,
  [sym_arithmetic_order] = sym_arithmetic_order,
  [sym_source_file] = sym_source_file,
  [sym_tape_header] = sym_tape_header,
  [sym_tape_mode] = sym_tape_mode,
  [sym_control_order] = sym_control_order,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_newline] = {
    .visible = true,
    .named = true,
  },
  [sym_tape_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPARENstraight_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPARENlooped_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_fixed_point] = {
    .visible = true,
    .named = true,
  },
  [sym_memory_order] = {
    .visible = true,
    .named = true,
  },
  [sym_op_noop] = {
    .visible = true,
    .named = true,
  },
  [sym_op_finish] = {
    .visible = true,
    .named = true,
  },
  [sym_op_signal] = {
    .visible = true,
    .named = true,
  },
  [sym_op_sign_test] = {
    .visible = true,
    .named = true,
  },
  [sym_op_transfer] = {
    .visible = true,
    .named = true,
  },
  [sym_op_search] = {
    .visible = true,
    .named = true,
  },
  [sym_op_layout] = {
    .visible = true,
    .named = true,
  },
  [sym_op_shift] = {
    .visible = true,
    .named = true,
  },
  [sym_arithmetic_order] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_tape_header] = {
    .visible = true,
    .named = true,
  },
  [sym_tape_mode] = {
    .visible = true,
    .named = true,
  },
  [sym_control_order] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(58);
      ADVANCE_MAP(
        '\n', 60,
        '"', 57,
        '(', 21,
        '*', 53,
        '0', 5,
        ';', 59,
        '+', 30,
        '-', 30,
      );
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '7')) ADVANCE(50);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(61);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == ')') ADVANCE(63);
      END_STATE();
    case 3:
      if (lookahead == ')') ADVANCE(62);
      END_STATE();
    case 4:
      if (lookahead == '.') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      END_STATE();
    case 5:
      if (lookahead == '0') ADVANCE(6);
      if (lookahead == '1') ADVANCE(28);
      if (lookahead == '2') ADVANCE(29);
      if (lookahead == '7') ADVANCE(31);
      if (lookahead == '8') ADVANCE(46);
      if (lookahead == '3' ||
          lookahead == '5') ADVANCE(45);
      END_STATE();
    case 6:
      if (lookahead == '0') ADVANCE(11);
      if (lookahead == '1') ADVANCE(12);
      if (lookahead == '2') ADVANCE(13);
      END_STATE();
    case 7:
      if (lookahead == '0') ADVANCE(66);
      END_STATE();
    case 8:
      if (lookahead == '0') ADVANCE(67);
      END_STATE();
    case 9:
      if (lookahead == '0') ADVANCE(68);
      END_STATE();
    case 10:
      if (lookahead == '0') ADVANCE(74);
      END_STATE();
    case 11:
      if (lookahead == '0') ADVANCE(7);
      END_STATE();
    case 12:
      if (lookahead == '0') ADVANCE(8);
      END_STATE();
    case 13:
      if (lookahead == '0') ADVANCE(9);
      END_STATE();
    case 14:
      if (lookahead == '0') ADVANCE(10);
      END_STATE();
    case 15:
      if (lookahead == 'a') ADVANCE(20);
      END_STATE();
    case 16:
      if (lookahead == 'd') ADVANCE(2);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 18:
      if (lookahead == 'g') ADVANCE(19);
      END_STATE();
    case 19:
      if (lookahead == 'h') ADVANCE(27);
      END_STATE();
    case 20:
      if (lookahead == 'i') ADVANCE(18);
      END_STATE();
    case 21:
      if (lookahead == 'l') ADVANCE(23);
      if (lookahead == 's') ADVANCE(26);
      END_STATE();
    case 22:
      if (lookahead == 'o') ADVANCE(24);
      END_STATE();
    case 23:
      if (lookahead == 'o') ADVANCE(22);
      END_STATE();
    case 24:
      if (lookahead == 'p') ADVANCE(17);
      END_STATE();
    case 25:
      if (lookahead == 'r') ADVANCE(15);
      END_STATE();
    case 26:
      if (lookahead == 't') ADVANCE(25);
      END_STATE();
    case 27:
      if (lookahead == 't') ADVANCE(3);
      END_STATE();
    case 28:
      if (lookahead == '1' ||
          lookahead == '2') ADVANCE(39);
      END_STATE();
    case 29:
      if (lookahead == '1' ||
          lookahead == '2') ADVANCE(40);
      END_STATE();
    case 30:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(4);
      END_STATE();
    case 31:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(73);
      END_STATE();
    case 32:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(69);
      END_STATE();
    case 33:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(70);
      END_STATE();
    case 34:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(72);
      END_STATE();
    case 35:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(71);
      END_STATE();
    case 36:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(75);
      END_STATE();
    case 37:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(65);
      END_STATE();
    case 38:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(64);
      END_STATE();
    case 39:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 40:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 41:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      END_STATE();
    case 42:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 43:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      END_STATE();
    case 44:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      END_STATE();
    case 45:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      END_STATE();
    case 46:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      END_STATE();
    case 47:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 48:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      END_STATE();
    case 49:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      END_STATE();
    case 50:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 51:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      END_STATE();
    case 52:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(49);
      END_STATE();
    case 53:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      END_STATE();
    case 54:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      END_STATE();
    case 55:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(54);
      END_STATE();
    case 56:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      END_STATE();
    case 57:
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(1);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_newline);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_tape_name);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_LPARENstraight_RPAREN);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_LPARENlooped_RPAREN);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_fixed_point);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_memory_order);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_op_noop);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_op_finish);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_op_signal);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_op_sign_test);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_op_transfer);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_op_search);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_op_layout);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_op_layout);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_op_shift);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_arithmetic_order);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_newline] = ACTIONS(1),
    [sym_tape_name] = ACTIONS(1),
    [anon_sym_LPARENstraight_RPAREN] = ACTIONS(1),
    [anon_sym_LPARENlooped_RPAREN] = ACTIONS(1),
    [sym_fixed_point] = ACTIONS(1),
    [sym_memory_order] = ACTIONS(1),
    [sym_op_noop] = ACTIONS(1),
    [sym_op_finish] = ACTIONS(1),
    [sym_op_signal] = ACTIONS(1),
    [sym_op_sign_test] = ACTIONS(1),
    [sym_op_transfer] = ACTIONS(1),
    [sym_op_search] = ACTIONS(1),
    [sym_op_layout] = ACTIONS(1),
    [sym_op_shift] = ACTIONS(1),
    [sym_arithmetic_order] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(8),
    [sym_tape_header] = STATE(3),
    [sym_control_order] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
    [sym_newline] = ACTIONS(7),
    [sym_tape_name] = ACTIONS(9),
    [sym_fixed_point] = ACTIONS(7),
    [sym_memory_order] = ACTIONS(7),
    [sym_op_noop] = ACTIONS(11),
    [sym_op_finish] = ACTIONS(11),
    [sym_op_signal] = ACTIONS(11),
    [sym_op_sign_test] = ACTIONS(11),
    [sym_op_transfer] = ACTIONS(11),
    [sym_op_search] = ACTIONS(11),
    [sym_op_layout] = ACTIONS(11),
    [sym_op_shift] = ACTIONS(11),
    [sym_arithmetic_order] = ACTIONS(7),
  },
  [STATE(2)] = {
    [sym_tape_mode] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(13),
    [sym_comment] = ACTIONS(3),
    [sym_newline] = ACTIONS(13),
    [sym_tape_name] = ACTIONS(13),
    [anon_sym_LPARENstraight_RPAREN] = ACTIONS(15),
    [anon_sym_LPARENlooped_RPAREN] = ACTIONS(15),
    [sym_fixed_point] = ACTIONS(13),
    [sym_memory_order] = ACTIONS(13),
    [sym_op_noop] = ACTIONS(13),
    [sym_op_finish] = ACTIONS(13),
    [sym_op_signal] = ACTIONS(13),
    [sym_op_sign_test] = ACTIONS(13),
    [sym_op_transfer] = ACTIONS(13),
    [sym_op_search] = ACTIONS(13),
    [sym_op_layout] = ACTIONS(13),
    [sym_op_shift] = ACTIONS(13),
    [sym_arithmetic_order] = ACTIONS(13),
  },
  [STATE(3)] = {
    [sym_tape_header] = STATE(4),
    [sym_control_order] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
    [sym_newline] = ACTIONS(19),
    [sym_tape_name] = ACTIONS(9),
    [sym_fixed_point] = ACTIONS(19),
    [sym_memory_order] = ACTIONS(19),
    [sym_op_noop] = ACTIONS(11),
    [sym_op_finish] = ACTIONS(11),
    [sym_op_signal] = ACTIONS(11),
    [sym_op_sign_test] = ACTIONS(11),
    [sym_op_transfer] = ACTIONS(11),
    [sym_op_search] = ACTIONS(11),
    [sym_op_layout] = ACTIONS(11),
    [sym_op_shift] = ACTIONS(11),
    [sym_arithmetic_order] = ACTIONS(19),
  },
  [STATE(4)] = {
    [sym_tape_header] = STATE(4),
    [sym_control_order] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
    [sym_newline] = ACTIONS(23),
    [sym_tape_name] = ACTIONS(26),
    [sym_fixed_point] = ACTIONS(23),
    [sym_memory_order] = ACTIONS(23),
    [sym_op_noop] = ACTIONS(29),
    [sym_op_finish] = ACTIONS(29),
    [sym_op_signal] = ACTIONS(29),
    [sym_op_sign_test] = ACTIONS(29),
    [sym_op_transfer] = ACTIONS(29),
    [sym_op_search] = ACTIONS(29),
    [sym_op_layout] = ACTIONS(29),
    [sym_op_shift] = ACTIONS(29),
    [sym_arithmetic_order] = ACTIONS(23),
  },
  [STATE(5)] = {
    [ts_builtin_sym_end] = ACTIONS(32),
    [sym_comment] = ACTIONS(3),
    [sym_newline] = ACTIONS(32),
    [sym_tape_name] = ACTIONS(32),
    [sym_fixed_point] = ACTIONS(32),
    [sym_memory_order] = ACTIONS(32),
    [sym_op_noop] = ACTIONS(32),
    [sym_op_finish] = ACTIONS(32),
    [sym_op_signal] = ACTIONS(32),
    [sym_op_sign_test] = ACTIONS(32),
    [sym_op_transfer] = ACTIONS(32),
    [sym_op_search] = ACTIONS(32),
    [sym_op_layout] = ACTIONS(32),
    [sym_op_shift] = ACTIONS(32),
    [sym_arithmetic_order] = ACTIONS(32),
  },
  [STATE(6)] = {
    [ts_builtin_sym_end] = ACTIONS(34),
    [sym_comment] = ACTIONS(3),
    [sym_newline] = ACTIONS(34),
    [sym_tape_name] = ACTIONS(34),
    [sym_fixed_point] = ACTIONS(34),
    [sym_memory_order] = ACTIONS(34),
    [sym_op_noop] = ACTIONS(34),
    [sym_op_finish] = ACTIONS(34),
    [sym_op_signal] = ACTIONS(34),
    [sym_op_sign_test] = ACTIONS(34),
    [sym_op_transfer] = ACTIONS(34),
    [sym_op_search] = ACTIONS(34),
    [sym_op_layout] = ACTIONS(34),
    [sym_op_shift] = ACTIONS(34),
    [sym_arithmetic_order] = ACTIONS(34),
  },
  [STATE(7)] = {
    [ts_builtin_sym_end] = ACTIONS(36),
    [sym_comment] = ACTIONS(3),
    [sym_newline] = ACTIONS(36),
    [sym_tape_name] = ACTIONS(36),
    [sym_fixed_point] = ACTIONS(36),
    [sym_memory_order] = ACTIONS(36),
    [sym_op_noop] = ACTIONS(36),
    [sym_op_finish] = ACTIONS(36),
    [sym_op_signal] = ACTIONS(36),
    [sym_op_sign_test] = ACTIONS(36),
    [sym_op_transfer] = ACTIONS(36),
    [sym_op_search] = ACTIONS(36),
    [sym_op_layout] = ACTIONS(36),
    [sym_op_shift] = ACTIONS(36),
    [sym_arithmetic_order] = ACTIONS(36),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(38), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(8)] = 0,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tape_header, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_control_order, 1, 0, 0),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tape_mode, 1, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tape_header, 2, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_witchr(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "witchr",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
